# -*- coding: utf-8 -*-
"""세차장.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mln4EjfYmulL3S67NIW2nIM5JI8jyKQ-
"""

!pip install gspread oauth2client pytesseract opencv-python streamlit

from google.colab import auth, files
import gspread
from google.oauth2 import service_account
import cv2
import pytesseract
import re
import streamlit as st
import tempfile
from PIL import Image

# 🔑 Google Sheets API 설정
auth.authenticate_user()
uploaded_key = files.upload()

json_key = list(uploaded_key.keys())[0]

credentials = service_account.Credentials.from_service_account_file(
    json_key, scopes=["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/drive"]
)
client = gspread.authorize(credentials)
spreadsheet = client.open("Oasis Customer Management")
worksheet = spreadsheet.worksheet("시트1")

# 🚗 Streamlit 웹 앱 실행
st.title("🚗 차량 번호판 인식 시스템")
uploaded_image = st.file_uploader("📸 차량 사진을 업로드하세요.", type=["jpg", "jpeg", "png"])

if uploaded_image is not None:
    image = Image.open(uploaded_image)
    st.image(image, caption="업로드된 이미지", use_column_width=True)

    with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as temp_image:
        temp_image.write(uploaded_image.getbuffer())
        temp_image_path = temp_image.name

    def recognize_license_plate(image_path):
        image = cv2.imread(image_path)
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        plate_text = pytesseract.image_to_string(gray, lang='eng')
        plate_number_match = re.findall(r'\d{2,3}[가-힣]\s?\d{4}', plate_text)
        return plate_number_match[0] if plate_number_match else None

    plate_number = recognize_license_plate(temp_image_path)

    if plate_number is None:
        plate_number = st.text_input("🚨 번호판 인식 실패! 차량 번호를 직접 입력하세요:")

    st.write(f"🚗 최종 차량 번호: {plate_number}")

    records = worksheet.get_all_records()
    customer_exists = any(record["Vehicle number"] == plate_number for record in records)

    if customer_exists:
        st.success("✅ 기존 고객입니다. 방문 기록을 업데이트합니다.")
    else:
        phone_number = st.text_input("📞 신규 고객입니다. 전화번호를 입력하세요:")
        if st.button("🚗 신규 고객 등록"):
            new_customer = [plate_number, phone_number, "2025-03-19", "2025-03-19", 1, "2025-03-19 10:25 (1)"]
            worksheet.append_row(new_customer)
            st.success(f"✅ 신규 고객이 등록되었습니다: {plate_number}")