[gcp_service_account]
type = "service_account"
project_id = "disco-bedrock-454208-g0"
private_key_id = "ba7f6063fc1c793472bebb4b64c73c65ef64a297"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmVw8N80eJBmGs
1dkaKU1nN8W7RRddd4JXruK6ovB6klSfUwp+NDe+5AVuEgYF7ACs06s/BX4pae09
9vLb+33GMwsh7yzcIL0lVz41dYIwKHNQi/F7GkgEXSo2YWUn3SAqbMW7HWw+3BMh
PVyZunMs2GwGJf5mRqwZPuU1dLXyD6LvZgiWYNq8l7KCOfdZ8nGZnJhhoul4uDtb
KAu/QbCPkcuWE3IFds7XgLVMb8GbVavj+4p3zT6Fdud+ESCbpATQdPBVZqe81iD6
Ost89Z4xNNcQo3lZ4PhTAw6F3WoW4UOJycMWY8dhCluoWkRlW0Jd/jJJGGelwlPY
uhvzei1ZAgMBAAECggEAA/9dnkE1e+aKXGP7RrStZoihmOGNMTLZEBBk5IVb8CYq
IHYXb3cDy/Og6cdHG8dTMNQZbndMU+R2ziFsLrs5h5TcdKFR26xxvz78gL5lNZET
TGFAmWvFRU2T4SCwFKgsyLg6fEe1vUD+uLLH0e34LKC6397z4TNbmXO4gHNgmAOc
Nmq8bTCkIB4OJRwcIogK370XOZVP4i2YZ4bGRB9DBHuwvpWIyL0T9FHiEy4YGwi3
YZlkrTqc0AjhupX/32VFL4eWAx6NXLpGg5aQtdmuTumSATXdddHeLAYpwoJ4GePj
XiBvXj52kIiuVXFsyIuJzCipzaFxGXTxhP5NCbZaAQKBgQDlaNJy6s3vNmH6+bz7
1D0Dh16Zk6MeGLQ2g5y3FwEovCCwkP+qWE1gqjkAKdmKgzOjc7MlJ24zrTr1Bopj
TbZV8yf0ncea4B55wA90R1D/oRrtfDabx+j6FyaSVM676LYjqcdfCppZMvM/LJFz
XiKbIrcwon9rObT35eLxCHOZGQKBgQC5ns2jAq8mkL7blxNKvMfkwsQYs5Sa28sJ
DFcwbX1MNyBJTIymT7lT8X3ugFg9vNCId/V0p3INgKzJwYaqORmjCBX08EGC+6ip
CY6amJDtIrtT6peqvxn3GYLMYHtR9kGs9QJPdKcAypN5wtp/HPMH1FCaOk5sl0fg
l1weubZ+QQKBgQDaLS64jAb+kcHtZsYM2nSMfpnBhV+EqAn8Ln9EwWQg0YplYgFE
iGZOoJVFSofR66WYtdiSZUWxb/a6QVYryyS16WL+iW/kI3HYaIhKFek6tIVfhtqI
nT89WfcdA/r5SwCuOjGaegMBAivE0SYjiktvLzz5zBFScLdjbAbBJUCLQQKBgFS+
C2PAdfZFXt0hu80DIr9tq9kbI10Pu0IGQEf7tJh3EmZkbFIBU7rfJX8dWSvWZ93l
5km7qHZBqKDzmWddajbkGiIZDc+e1QFXO6OYw5F/qcZF87ggRtpo6y4jXimtI46y
zLs5poTV9z4/l0ExFkMcyy+eLu+koUwHzia44ngBAoGAa59LQWY1xQ2P86na21VC
x0cAYE6uPqVMQV+a7VysqCOFiGyLRlpcTl2Audh5RHZ1VZK5ub43Wn5KhrSQKJhh
YFZHIoelXPEwp9h6Pm03uCVtJKGvXJmHCVFpT2CMiEVTBYEq2C+xoa5T6+jNZS/p
KbuiSCZzXwQKAJqSsvp8Pvc=
-----END PRIVATE KEY-----"""
client_email = "oasis-customer-management@disco-bedrock-454208-g0.iam.gserviceaccount.com"
client_id = "100261804748589083477"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/oasis-customer-management@disco-bedrock-454208-g0.iam.gserviceaccount.com"
